HolidaysBundle\Entity\Spend:
    type: entity
    table: null
    repositoryClass: HolidaysBundle\Repository\SpendRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        spendType:
            type: string
            length: '50'
            column: spend_type
        spendLibel:
            type: string
            length: '100'
            column: spend_libel
        spendDate:
            type: datetime
            column: spend_date
        spendMontant:
            type: decimal
            precision: '9'
            scale: '2'
            column: spend_montant
        spendGroupIndiv:
            type: boolean
            nullable: true
            column: spend_groupindiv
        spendPhoto:
            type: string
            length: '20'
            nullable: true
            column: spend_photo
    manyToOne:
        spendUserId:
            targetEntity: HolidaysBundle\Entity\User
            joinColumn:
                name: spend_userid
                referenceColumnName: id
        spendEventId:
            targetEntity: HolidaysBundle\Entity\Event
            joinColumn:
                name: spend_eventid
                referenceColumnName: id
    lifecycleCallbacks:
        prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [ preUpload, setUpdatedAtValue ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]

