# src/[AppBundle]/Resources/config/doctrine/User.orm.yml
HolidaysBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nomPrenom:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
