spend_index:
    path:     /
    defaults: { _controller: "HolidaysBundle:Spend:index" }
    methods:  GET

spend_show:
    path:     /{id}/show
    defaults: { _controller: "HolidaysBundle:Spend:show" }
    methods:  GET

spend_new:
    path:     /new
    defaults: { _controller: "HolidaysBundle:Spend:new" }
    methods:  [GET, POST]

spend_edit:
    path:     /{id}/edit
    defaults: { _controller: "HolidaysBundle:Spend:edit" }
    methods:  [GET, POST]

spend_delete:
    path:     /{id}/delete
    defaults: { _controller: "HolidaysBundle:Spend:delete" }
    methods:  DELETE
