<?php

namespace HolidaysBundle\Repository;

/**
 * SpendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpendRepository extends \Doctrine\ORM\EntityRepository
{
}
